### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by giosh94mhz** [Smart-Core/AcceleratorCacheBundle#10]
Sorry for the issue, I know it's boring when someone asks. Anyway, there are some features/fixes pending and the last relase is from January.

Anything that prevent a new release? May I help in this case?

**Comment by kbond** [comment]
Agreed, a new release would be helpful.

**Comment by Smart-Core** [comment]
@giosh94mhz, Greetings! Thank you for your interest for my project! A new release is a good thing, and I'd like to clarify the situation. Do you want to make a pull-request or point to some particular qualities, that you would like to have in the next release?

**Comment by giosh94mhz** [comment]
@Smart-Core I was thinking at a very simple 1.1.0 release, since there is my previous PR for custom curl options and other fixes, like php 5.3 compatibility.

I've used this bundle for a full year without problems, so I think that there is no need to rush in major refactoring. Anyway, sooner or later I think that the bundle will need PSR-7 support in the configuration, so this is something which you could keep in consideration.

**Comment by kbond** [comment]
Yeah, there have been 18 commits since 1.0.6: https://github.com/Smart-Core/AcceleratorCacheBundle/compare/1.0.6...master
