### ISSUE TITLE
How to set multi hosts ?

### ISSUE THREAD

**Issue by AlexandreHagen** [Smart-Core/AcceleratorCacheBundle#16]
Hi 

I would like to know if it is possible to set multi-hosts. Indeed, I got two dev servers with two different host names. 
It's possible to use AcceleratorCacheBundle in that way ? 

Thanks.

**Comment by AlexandreHagen** [comment]
Up ?

**Comment by BoShurik** [comment]
You mean one code base for two different domains? I think, you only need to clear the cache only on one of them.

**Comment by AlexandreHagen** [comment]
No, I have three different domains: One for production, on for development (online), on for development  (local). 
I would like to have two domains in `config_dev.yml`

**Comment by BoShurik** [comment]
Why not set this parameter in `parameters.yml`?

``` yaml
parameters:
    host: app.local
```

and in `config.yml`

``` yaml
accelerator_cache:
    host:    %host%
    web_dir: %kernel.root_dir%/../web
```

**Comment by AlexandreHagen** [comment]
Perfect I didn't have think about that solution. Thanks @BoShurik !
