### ISSUE TITLE
Exception with empty message

### ISSUE THREAD

**Issue by icamys** [Smart-Core/AcceleratorCacheBundle#22]
Getting exception with empty message:

> $ ./bin/console cache:accelerator:clear -vv
>
>                      
>  [RuntimeException]  
>                      
>
> Exception trace:
 () at /home/cdn/www/vendor/smart-core/accelerator-cache-bundle/Command/AcceleratorCacheClearCommand.php:46
 SmartCore\Bundle\AcceleratorCacheBundle\Command\AcceleratorCacheClearCommand->execute() at /home/cdn/www/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /home/cdn/www/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:846
 Symfony\Component\Console\Application->doRunCommand() at /home/cdn/www/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:191
 Symfony\Component\Console\Application->doRun() at /home/cdn/www/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:80
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /home/cdn/www/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:122
 Symfony\Component\Console\Application->run() at /home/cdn/www/bin/console:29

Using:

* php7
* Symfony 3.2

**Comment by bubnov-mikhail** [comment]
+1
Same problem

**Comment by bubnov-mikhail** [comment]
Found solvation:
Check your nginx or apache config - it must allow apc-.*.php to be processed as script, not plain file
Also check that console user is allowed to write files in web/

**Comment by Smart-Core** [comment]
I can't repruduce this error, how to do this?
