### ISSUE TITLE
File is not writable

### ISSUE THREAD

**Issue by uirapuru** [Smart-Core/AcceleratorCacheBundle#3]
I think that this commit:

https://github.com/Smart-Core/AcceleratorCacheBundle/commit/1edc3f515dffb1677229227d1a3eee06c859da2b

has broken command script. There's a check if notexisting file is writable, but it's created afterwards and there's an error.

**Comment by tobias-nawa** [comment]
I can confirm that.

**Comment by bassrock** [comment]
Confirm as well @Smart-Core any fix in sight?

**Comment by kbond** [comment]
Also experiencing this... @iwankgb can you fix?
